debug=True #is app in debug stage
log=None #logger class.will be initiallized with app
EXCEPTION_NOTIFY=True #show message in log
handler=None#exception handler
plugins_folder="plugins"#folder where plugins stored
components_folder="components"
argv=None#argv
CRASH_ON_EXCEPTIONS=True
SHOW_EVENTS_IN_LOG=True#if this True all events will be logged
